version: "3"
services:
  springboot:
    image: hobby/hobby-back
    build: .
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/hobby
      SPRING_PROFILES_ACTIVE: docker
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo
    container_name: mongodb-img
    ports:
      - 27017:27017
    hostname: mongo
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge